# Generated by Django 4.1.2 on 2022-11-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_baseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('minzu', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('adress', models.CharField(max_length=150)),
                ('born_place', models.CharField(default='城市', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='艾叫', max_length=500)),
                ('minzu', models.CharField(default='傣', max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('age', models.IntegerField(default=18)),
                ('tel', models.IntegerField(default=125)),
                ('adress', models.CharField(default='景洪', max_length=150)),
                ('dhamma_name', models.CharField(default='都比', max_length=500)),
                ('title2', models.CharField(default='沙马内拉', max_length=50)),
                ('teacher_id', models.IntegerField(default=1)),
                ('monk_date', models.DateTimeField()),
                ('monk_temple', models.CharField(default='曼弄', max_length=500)),
                ('sila_teacher', models.CharField(default='马哈国', max_length=500)),
                ('grade', models.IntegerField(default=1)),
                ('base_id', models.IntegerField(default=1)),
                ('religion_id', models.IntegerField(default=1)),
                ('study_level', models.CharField(default=1, max_length=500)),
                ('student_type', models.CharField(default='全日制', max_length=500)),
                ('school_lenth', models.IntegerField(default=3)),
                ('enrol_date', models.DateTimeField()),
                ('middle_exam', models.BooleanField(default=True)),
                ('graduate_school', models.CharField(max_length=50)),
                ('relationship1', models.CharField(default='父亲', max_length=50)),
                ('fml_name1', models.CharField(default='岩丙国', max_length=50)),
                ('minzhu1', models.CharField(default='傣', max_length=50)),
                ('job_info1', models.CharField(default='农民', max_length=50)),
                ('fml_tel1', models.IntegerField(default=188)),
                ('relationship2', models.CharField(default='母亲', max_length=50)),
                ('fml_name2', models.CharField(default='玉香', max_length=50)),
                ('minzhu2', models.CharField(default='傣', max_length=50)),
                ('job_info2', models.CharField(default='农民', max_length=50)),
                ('fml_tel2', models.IntegerField(default=188)),
                ('relationship3', models.CharField(default='哥哥', max_length=50)),
                ('fml_name3', models.CharField(default='艾放', max_length=50)),
                ('minzhu3', models.CharField(default='傣', max_length=50)),
                ('job_info3', models.CharField(default='职员', max_length=50)),
                ('fml_tel3', models.IntegerField(default=134)),
            ],
        ),
        migrations.CreateModel(
            name='student_religionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhamma_name', models.CharField(max_length=500)),
                ('title2', models.CharField(default='沙马内拉', max_length=50)),
                ('teacher_id', models.IntegerField()),
                ('monk_date', models.DateTimeField()),
                ('monk_temple', models.CharField(max_length=500)),
                ('sila_teacher', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='student_schoolIfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('base_id', models.IntegerField()),
                ('religion_id', models.IntegerField()),
                ('study_level', models.CharField(max_length=500)),
                ('student_type', models.CharField(max_length=500)),
                ('school_lenth', models.IntegerField()),
                ('enrol_date', models.DateTimeField()),
                ('middle_exam', models.BooleanField(default=True)),
                ('graduate_school', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('minzhu', models.CharField(max_length=50)),
                ('job_info', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuManage.student_info')),
            ],
        ),
    ]
