# Generated by Django 4.1.2 on 2022-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='fml_name4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_name5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_tel4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_tel5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_info',
            name='job_info4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='job_info5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='minzhu4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='minzhu5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='relationship4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_info',
            name='relationship5',
            field=models.CharField(default='', max_length=50),
        ),
    ]
