# Generated by Django 4.1.2 on 2022-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0002_student_info_fml_name4_student_info_fml_name5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='fml_name4',
            field=models.CharField(default='玉光', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_name5',
            field=models.CharField(default='玉香', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel4',
            field=models.IntegerField(default=122),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel5',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='job_info4',
            field=models.CharField(default='妹妹', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='job_info5',
            field=models.CharField(default='职员', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='minzhu4',
            field=models.CharField(default='傣', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='minzhu5',
            field=models.CharField(default='傣', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship4',
            field=models.CharField(default='姐姐', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship5',
            field=models.CharField(default='妹妹', max_length=50),
        ),
    ]
