# Generated by Django 4.1.2 on 2022-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0006_alter_student_info_fml_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='fml_name5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel5',
            field=models.IntegerField(blank=True, default=123),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='job_info5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='minzhu5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
