# Generated by Django 4.1.2 on 2022-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0009_alter_student_info_fml_tel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='fml_name4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='minzhu4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
