# Generated by Django 4.1.2 on 2022-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0010_alter_student_info_fml_name4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
