# Generated by Django 4.1.2 on 2022-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0014_alter_student_info_fml_tel1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='FamilyAc_m_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='FamilyAc_p_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='ID_b_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='ID_f_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='clothes_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='jiasha_photo',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='security',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
