# Generated by Django 4.1.2 on 2022-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0015_student_info_familyac_m_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='FamilyAc_m_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='FamilyAc_p_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='ID_b_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='ID_f_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='clothes_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='jiasha_photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='security',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
