# Generated by Django 4.1.2 on 2022-11-11 15:12

from django.db import migrations, models
import stuManage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0017_alter_student_info_familyac_m_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='sfid',
            field=models.CharField(default='', max_length=18, unique=True, validators=[stuManage.models.IDValidator], verbose_name='身份证号码'),
        ),
    ]
