# Generated by Django 4.1.2 on 2022-11-12 13:53

from django.db import migrations, models
import stuManage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0018_student_info_sfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='sfid',
            field=models.CharField(blank=True, default='', max_length=18, null=True, unique=True, validators=[stuManage.models.IDValidator], verbose_name='身份证号码'),
        ),
    ]
