# Generated by Django 4.1.2 on 2022-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0019_alter_student_info_sfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='sfid',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='身份证号码'),
        ),
    ]
