# Generated by Django 4.1.2 on 2022-11-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0020_alter_student_info_sfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='relationship1',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship2',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship3',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship4',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='relationship5',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
