# Generated by Django 4.1.2 on 2023-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0022_alter_student_info_relationship1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='adress',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='dhamma_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fml_tel5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='monk_temple',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='sila_teacher',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_type',
            field=models.CharField(choices=[('全日制', '全日制'), ('非全日制', '非全日制')], default='全日制', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='study_level',
            field=models.CharField(default='中专', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='tel',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='title2',
            field=models.CharField(choices=[('沙马内拉', '沙马内拉'), ('比库', '比库')], default='沙马内拉', max_length=50),
        ),
    ]
