# Generated by Django 4.1.2 on 2023-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0023_alter_student_info_adress_alter_student_info_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='fml_id1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='hukou',
            field=models.CharField(choices=[('农村户口', '农村户口'), ('城镇户口', '城镇户口')], default='', max_length=150),
        ),
    ]
