# Generated by Django 4.1.2 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0024_student_info_fml_id1_student_info_fml_id2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='fml_id1',
            new_name='fml_id_b1',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='fml_id2',
            new_name='fml_id_b2',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='fml_id3',
            new_name='fml_id_b3',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='fml_id4',
            new_name='fml_id_b5',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='fml_id5',
            new_name='fml_id_f1',
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id_f2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id_f3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id_f4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id_f5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_info',
            name='fml_id_n4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
