# Generated by Django 4.1.2 on 2023-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0025_rename_fml_id1_student_info_fml_id_b1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=900)),
            ],
        ),
    ]
