# Generated by Django 4.1.2 on 2023-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManage', '0026_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='姓名'),
        ),
    ]
