# Generated by Django 3.1.14 on 2022-09-16 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 9, 16, 14, 25, 38, 604063, tzinfo=utc))),
            ],
        ),
    ]
