# Generated by Django 4.1.2 on 2022-10-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
